### ISSUE TITLE
It no do

### ISSUE THREAD

**Issue by PrimaryIan210** [tairabiteru/LunaHack#1] opened 2021-01-13 19:00 UTC
`Traceback (most recent call last):

  File "LunaHack.py", line 383, in <module>

  File "LunaHack.py", line 354, in process

  File "shutil.py", line 730, in rmtree

  File "shutil.py", line 589, in _rmtree_unsafe

  File "shutil.py", line 586, in _rmtree_unsafe

FileNotFoundError: [WinError 3] The system cannot find the path specified: 'original/'

[17452] Failed to execute script LunaHack
`

**Comment by tairabiteru** [comment] 2021-01-13 19:09
Caused by line 354:
`shutil.rmtree(self.original)`

The blunder here was when I attempted to remove a path which had already been proven to not exist. The fix is simple, but I can't release an update until later today.

**Comment by tairabiteru** [comment] 2021-01-13 21:25
This has been fixed in LunaHack 6.2.

**Closed as completed** 2021-01-13 21:25 UTC
Labels: bug
